### ISSUE TITLE
评论的代码处理貌似出错了。

### ISSUE THREAD

**Issue by gMan1990** [hundan2020/v2exMarkdown#1]
<img width="1111" alt="WX20190919-143546@2x" src="https://user-images.githubusercontent.com/5050994/65219253-cabb8480-daea-11e9-8d90-387fdb578e06.png">

- https://www.v2ex.com/t/601728?p=1#r_7914247
    - span.hljs-built_in 递归了
    - `finale-rest` 行内代码不应该换行

**Comment by hundan2020** [comment]
已修复

**Comment by gMan1990** [comment]
- 行内代码的多种写法
    - `` ` Hello. ` ``
    - ``` `` There is a literal backtick (`) here. `` ```

```text
- 行内代码的多种写法
    - `` ` Hello. ` ``
    - ``` `` There is a literal backtick (`) here. `` ```
```

**Comment by hundan2020** [comment]
@gMan1990 还有bug吗 没有的话我close咯
